# Generated by Django 2.1.5 on 2019-05-14 22:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0003_auto_20180904_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'Wrecker Social 2019 Super Fun TIME!", max_length=100, verbose_name='Event Name')),
                ('slug', models.SlugField(help_text="URL to the event ticket registration thing. Example: 'wrecker-social-2019-okay-great' ", max_length=100, verbose_name='Event Slug')),
                ('description', models.TextField(help_text="Blurb of text shown in the description. You can use <a target='_blank' href='https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'>Markdown Code</a> to format the document.", max_length=100, verbose_name='Event Description')),
                ('open_date', models.DateTimeField(blank=True, help_text='The date/time that the registration form becomes available. If you set it to blank, registration is open now.', null=True, verbose_name='Registration Opens On')),
                ('closes_date', models.DateTimeField(blank=True, help_text='The date/time that the registration form becomes available. If you set it to blank, registration will never close.', null=True, verbose_name='Registration Closes On')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tickets')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ticket Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Ticket Email')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid for this transaction', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount Paid')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Paid')),
            ],
        ),
    ]
