# Generated by Django 2.1.5 on 2019-05-15 02:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketpurchase_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price of event to charge for a ticket.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount Paid'),
        ),
    ]
