# Generated by Django 2.1.5 on 2019-05-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketevent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='description',
            field=models.TextField(help_text="Blurb of text shown in the description. You can use <a target='_blank' href='https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'>Markdown Code</a> to format the document.", verbose_name='Event Description'),
        ),
    ]
