# Generated by Django 2.1.5 on 2019-05-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190514_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='name',
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='derby_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Derby Name'),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='real_name',
            field=models.CharField(default='', max_length=100, verbose_name='Real Name'),
            preserve_default=False,
        ),
    ]
