# Generated by Django 2.0.7 on 2018-08-28 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['league', 'text']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='userlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag Color'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='message',
            field=models.TextField(help_text='Some notes or messages to keep on hand for this user. These notes are NOT viewable by the user.', verbose_name='User Note'),
        ),
    ]
