# Generated by Django 2.0.7 on 2018-08-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180828_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='group',
            field=models.CharField(default='note', max_length=50, verbose_name='Message Group'),
        ),
    ]
