# Generated by Django 2.0.3 on 2018-03-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180320_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='derby_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Derby Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='derby_number',
            field=models.CharField(blank=True, max_length=4, verbose_name='Derby Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last Name'),
        ),
    ]
