# Generated by Django 2.0.6 on 2018-07-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20180703_1955'),
        ('users', '0002_auto_20180703_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default=1, on_delete='Organization', to='league.Organization'),
            preserve_default=False,
        ),
    ]
