# Generated by Django 2.0.7 on 2018-08-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlog_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-date']},
        ),
    ]
