# Generated by Django 2.0.6 on 2018-07-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default=1, on_delete='Organization', to='league.Organization'),
        ),
    ]
