# Generated by Django 2.0.6 on 2018-07-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_auto_20180706_1549'),
        ('users', '0005_auto_20180706_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='league',
            field=models.ForeignKey(blank=True, default=1, on_delete='League', to='league.League'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, default=1, on_delete='Organization', to='league.Organization'),
        ),
    ]
