# Generated by Django 2.1.1 on 2019-01-22 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0003_auto_20180904_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this Election', max_length=50)),
                ('description', models.TextField(help_text='Description of this election to the members.')),
                ('slug', models.SlugField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Election Creation Date')),
                ('start_date', models.DateTimeField(help_text='Start date for this election')),
                ('end_date', models.DateTimeField(help_text='End date for this election')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('allow_write_in', models.BooleanField(default=False)),
                ('allow_comment', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='voting.Election')),
            ],
        ),
        migrations.CreateModel(
            name='VotingInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_invite', to='voting.Election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='voting.Election')),
            ],
        ),
        migrations.CreateModel(
            name='VotingResponseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_answer', to='voting.ElectionQuestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_answer', to='voting.VotingResponse')),
            ],
        ),
        migrations.AddField(
            model_name='electionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='voting.ElectionQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='votinginvite',
            unique_together={('user', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='election',
            unique_together={('slug', 'league')},
        ),
    ]
