# Generated by Django 2.0.7 on 2018-07-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this legal document.', max_length=100, verbose_name='Document Name')),
                ('slug', models.CharField(blank=True, max_length=100, verbose_name='Slug')),
                ('date', models.DateField(help_text='Effective date of this legal document.', verbose_name='Effective Date')),
                ('content', models.TextField(help_text="Plaintext version of the legal document. You can use <a target='_blank' href='https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'>Markdown Code</a> to format the document.", verbose_name='Document Content')),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.LegalDocument')),
            ],
            options={
                'ordering': ['agree_date', 'document__name'],
            },
        ),
    ]
