# Generated by Django 2.0.6 on 2018-07-12 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0012_remove_league_default_late_day_diff'),
        ('registration', '0013_auto_20180712_1229'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this legal document.', max_length=100, verbose_name='Document Name')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('date', models.DateField(help_text='Effective date of this legal document.', verbose_name='Effective Date')),
                ('content', models.TextField(help_text='Plaintext version of the legal document.', verbose_name='Document Content')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.LegalDocument')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.RegistrationEvent')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.RegistrationData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agree_date', 'document__name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together={('slug', 'league')},
        ),
    ]
