# Generated by Django 2.1.1 on 2018-09-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_auto_20180820_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalsignature',
            name='agreed_by',
            field=models.CharField(default='participant', help_text="Typically this is either 'participant' or 'guardian', signifying who agreed to the document.", max_length=20, verbose_name='Agreed To By'),
        ),
    ]
