# Generated by Django 2.0.6 on 2018-07-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_auto_20180712_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='content',
            field=models.TextField(help_text="Plaintext version of the legal document. You can use <a target='_blank' href='https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'>Markdown Code</a> to format the document.", verbose_name='Document Content'),
        ),
    ]
