# Generated by Django 2.0.6 on 2018-06-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'Wreckers', 'Juniors', 'Madison Roller Derby', etc.", max_length=50, verbose_name='Organization Name')),
                ('slug', models.CharField(help_text="Example: 'mrd', 'wreckers', 'juniors'. DO NOT CHANGE.", max_length=20, verbose_name='Organization Slug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'Wreckers', 'Juniors', 'Madison Roller Derby', etc.", max_length=50, verbose_name='Organization Name')),
                ('slug', models.CharField(help_text="Example: 'mrd', 'wreckers', 'juniors'. DO NOT CHANGE.", max_length=20, verbose_name='Organization Slug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='league',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Organization'),
        ),
    ]
