# Generated by Django 2.0.7 on 2018-09-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='email_footer',
        ),
        migrations.RemoveField(
            model_name='league',
            name='email_header',
        ),
        migrations.AddField(
            model_name='league',
            name='style_color_one',
            field=models.CharField(blank=True, help_text="First color for custom theme for this league. Default is '#F9FC69'.", max_length=20, verbose_name='Style Color #1'),
        ),
        migrations.AddField(
            model_name='league',
            name='style_color_two',
            field=models.CharField(blank=True, help_text="Second color for custom theme for this league. Default is '#35E5F4'.", max_length=20, verbose_name='Style Color #2'),
        ),
        migrations.AddField(
            model_name='league',
            name='style_email_font',
            field=models.CharField(blank=True, help_text="The font to use for branding the logo in emails. Default is 'Lucida Sans Unicode', 'Lucida Grande', sans-serif'", max_length=100, verbose_name='Email Font CSS Name'),
        ),
        migrations.AddField(
            model_name='league',
            name='style_header_font_css',
            field=models.CharField(blank=True, help_text="The font-face CSS to use for branding the league name in the header. Default is 'Lobster, cursive'.", max_length=100, verbose_name='Header Font Google Font CSS Name'),
        ),
        migrations.AddField(
            model_name='league',
            name='style_header_font_name',
            field=models.CharField(blank=True, help_text="The name of the font to use when loading the google font to use for the league name in the header. Default is 'Lobster'.", max_length=100, verbose_name='Header Font Google Font Name'),
        ),
    ]
