# Generated by Django 2.0.6 on 2018-07-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name'], 'permissions': (('member', 'Active member of league.'), ('billing_admin', 'Can send bills and manage dues.'), ('roster_admin', 'Can manage user profiles and assign people to teams.'), ('registration_admin', 'Can manage registration system and send invites.'), ('settings_admin', 'Can manage league settings and email templates.'))},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': (('member', 'Active member of organization.'), ('admin', 'Can manage organization settings, create leagues and more.'))},
        ),
    ]
