# Generated by Django 2.0.6 on 2018-07-04 00:55

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20180703_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='default_address_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], help_text='Default state choice on Registration forms.', max_length=2),
        ),
        migrations.AddField(
            model_name='league',
            name='stripe_private_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Private API key for Stripe', verbose_name='Stripe Private Key'),
        ),
        migrations.AddField(
            model_name='league',
            name='stripe_public_key',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Public API key for Stripe', verbose_name='Stripe Public Key'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(help_text="Example: 'Wreckers', 'Juniors', 'Madison Roller Derby', etc.", max_length=50, verbose_name='League Name'),
        ),
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.CharField(help_text="Example: 'mrd', 'wreckers', 'juniors'. DO NOT CHANGE.", max_length=20, verbose_name='League Slug'),
        ),
    ]
