# Generated by Django 2.0.6 on 2018-07-04 04:06

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_league_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='stripe_private_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Private API key for Stripe.com. Used for charging credit cards.', max_length=100, verbose_name='Stripe Private Key'),
        ),
        migrations.AlterField(
            model_name='league',
            name='stripe_public_key',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Private API key for Stripe.com. Used for charging credit cards.', max_length=100, verbose_name='Stripe Public Key'),
        ),
    ]
