# Generated by Django 2.0.6 on 2018-07-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20180703_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name'], 'permissions': (('league_admin', 'Can manage league settings and email templates.'), ('billing_manager', 'Can send bills and manage dues.'), ('roster_manager', 'Can manage user profiles and assign people to teams.'), ('registration_manager', 'Can manage registration system and send invites.'), ('survey_manager', 'Can manage voting and surveys.'), ('event_manager', 'Can manage special event pages.'), ('league_member', 'Active member of league.'))},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': (('league_admin', 'Can manage organization settings, create leagues and more.'),)},
        ),
    ]
