# Generated by Django 2.0.6 on 2018-07-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20180705_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='email_cc_address',
            field=models.EmailField(blank=True, help_text="If you would like all emails sent from this league to be CC'd to an email, enter one here. Leave blank to disable.", max_length=100, verbose_name='CC Emails To'),
        ),
        migrations.AddField(
            model_name='league',
            name='email_footer',
            field=models.TextField(blank=True, help_text='Custom header for all emails sent from this system.', verbose_name='Email Header'),
        ),
        migrations.AddField(
            model_name='league',
            name='email_from_address',
            field=models.EmailField(default='demo@silvers.net', help_text='The email address all emails from this league will be from.', max_length=100, verbose_name='Email From Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='email_from_name',
            field=models.CharField(blank=True, help_text="The name of the person or account sending email. Example 'MRD Training'.", max_length=100, verbose_name='Email From Name'),
        ),
        migrations.AddField(
            model_name='league',
            name='email_header',
            field=models.TextField(blank=True, help_text='Custom header for all emails sent from this system.', verbose_name='Email Header'),
        ),
        migrations.AddField(
            model_name='league',
            name='short_name',
            field=models.CharField(default='Demo', help_text="Example: 'MWD', 'Juniors', 'MRD', etc. Something short.", max_length=50, verbose_name='Short Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.CharField(blank=True, help_text="Example: 'mrd', 'wreckers', 'juniors'. DO NOT CHANGE.", max_length=20, verbose_name='League Slug'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text="Example: 'Madison Roller Derby', etc.", max_length=50, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(blank=True, help_text="Example: 'mrd', 'wreckers', 'juniors'. DO NOT CHANGE.", max_length=20, unique=True, verbose_name='Organization Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('slug', 'organization')},
        ),
    ]
