# Generated by Django 2.0.6 on 2018-07-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20180706_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='email_footer',
            field=models.TextField(blank=True, help_text='Custom header design HTML (bottom) for all emails sent from this system.', verbose_name='Email Footer'),
        ),
        migrations.AlterField(
            model_name='league',
            name='email_header',
            field=models.TextField(blank=True, help_text='Custom header design HTML for all emails sent from this system.', verbose_name='Email Header'),
        ),
    ]
