# Generated by Django 2.0.7 on 2018-08-20 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
        ('billing', '0001_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsubscription',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.RegistrationEvent'),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Roster'),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingperiodcustompaymentamount',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingGroup'),
        ),
        migrations.AddField(
            model_name='billingperiodcustompaymentamount',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingPeriod'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='dues_amounts',
            field=models.ManyToManyField(through='billing.BillingPeriodCustomPaymentAmount', to='billing.BillingGroup'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.RegistrationEvent'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='billinggroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingGroup'),
        ),
        migrations.AddField(
            model_name='billinggroupmembership',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='billinggroupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billinggroup',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AlterUniqueTogether(
            name='userstripecard',
            unique_together={('user', 'league')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'league', 'billing_period')},
        ),
        migrations.AlterUniqueTogether(
            name='billingperiodcustompaymentamount',
            unique_together={('group', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='billinggroupmembership',
            unique_together={('user', 'league')},
        ),
        migrations.AlterUniqueTogether(
            name='billinggroup',
            unique_together={('name', 'league')},
        ),
    ]
