# Generated by Django 2.0.7 on 2018-08-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180820_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstripecard',
            name='card_num_failures',
            field=models.IntegerField(default=0, verbose_name='Number of times this card has failed'),
        ),
    ]
