# Generated by Django 2.0.7 on 2018-08-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_userstripecard_card_num_failures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingPeriod'),
        ),
    ]
