# Generated by Django 2.1.1 on 2018-09-07 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20180901_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingsubscription',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterField(
            model_name='billingsubscription',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Roster'),
        ),
    ]
