# Generated by Django 2.0.6 on 2018-06-27 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'Summer Skating', 'MRD 2018 Registration'", max_length=50, verbose_name='Event Name')),
                ('slug', models.SlugField(help_text="Example: 'summer-skating-2018', is used for the registration URL.", verbose_name='Event Slug')),
                ('registration_open_datetime', models.DateTimeField(blank=True, help_text='The date/time that the registration form becomes available. If you set it to blank, registration is open now.', verbose_name='Registration Opens At')),
                ('registration_closes_datetime', models.DateTimeField(blank=True, help_text='The date/time that the registration form becomes available. If you set it to blank, registration will never close.', verbose_name='Registration Closes At')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('send_datetime', models.DateTimeField()),
                ('expiry', models.DateTimeField()),
                ('completed', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
