# Generated by Django 2.0.6 on 2018-07-03 19:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('contact_last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('contact_address1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('contact_address2', models.CharField(max_length=100, verbose_name='Address 2')),
                ('contact_city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, verbose_name='State')),
                ('contact_zipcode', models.CharField(max_length=11, verbose_name='Zip Code')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Phone Number')),
                ('derby_name', models.CharField(max_length=100, verbose_name='Derby Name')),
                ('derby_number', models.CharField(max_length=10, verbose_name='Derby Number')),
                ('derby_pronoun', models.CharField(max_length=50, verbose_name='Personal Pronoun')),
                ('derby_insurance_type', models.CharField(max_length=50, verbose_name='Derby Insurance')),
                ('derby_insurance_number', models.CharField(max_length=50, verbose_name='Derby Insurance Number')),
                ('emergency_date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('emergency_contact', models.CharField(max_length=100, verbose_name='Derby Name')),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Emergency Phone Contact')),
                ('emergency_relationship', models.CharField(max_length=100, verbose_name='Emergency Relationship')),
                ('emergency_hospital', models.CharField(max_length=100, verbose_name='Preferred Hospital')),
                ('emergency_allergies', models.TextField(verbose_name='Allergies and Medical Conditions')),
                ('invite', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registration.RegistrationInvite')),
            ],
        ),
    ]
