# Generated by Django 2.0.7 on 2018-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registrationevent_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationevent',
            name='invite_blurb',
            field=models.TextField(blank=True, help_text="Text shown in the <strong>invite email</strong>. Could be used for communicating some details about the event, invite or signup system. You can use <a target='_blank' href='https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'>Markdown Code</a> to format the document.", verbose_name='Invite Blurb'),
        ),
    ]
