# Generated by Django 2.0.7 on 2018-09-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registrationevent_invite_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='derby_insurance_number',
            field=models.CharField(blank=True, help_text='Derby insurance details. Insurance may not be required, depending on your skating level.', max_length=50, verbose_name='Derby Insurance Number'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='derby_insurance_type',
            field=models.ForeignKey(blank=True, help_text='If you have Derby insurance, specify it here. Insurance may not be required, depending on your skating level.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.InsuranceType'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='derby_name',
            field=models.CharField(blank=True, help_text="Not required for new skaters. Choose it later if you would like. The general rule of thumb is if it's not used in your home league, <a href='http://www.derbyrollcall.com' target='_blank'>or someone you will likely never play</a>, then it's probably OK.", max_length=100, verbose_name='Derby Name'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='derby_number',
            field=models.CharField(blank=True, help_text="Not required for new skaters. Choose it later if you would like. <a href='https://docs.google.com/document/d/1wQmQsOdMiTe3T8sHmZ3yQmUJQP9mZqLr_9e_I_zjwfI/edit?ts=5b8ae478' target='_blank'>Here are some tips for picking your derby number.</a>", max_length=10, verbose_name='Derby Number'),
        ),
    ]
