# Generated by Django 2.0.8 on 2018-09-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180904_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='parent1_address1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent1_address2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent1_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent1_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Primary Parent/Guardian Email Address'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent1_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Parent/Guardian Name'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent1_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Primary Parent/Guardian Phone Number'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent1_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent1_zipcode',
            field=models.CharField(blank=True, max_length=11, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent2_address1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent2_address2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent2_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent2_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Second Parent/Guardian Email Address'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent2_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Second Parent/Guardian Name'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent2_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Second Parent/Guardian Phone Number'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent2_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='parent2_zipcode',
            field=models.CharField(blank=True, max_length=11, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='registrationevent',
            name='form_type',
            field=models.CharField(choices=[('standard', 'Standard Registration'), ('minor', 'Minor Registration with Parent/Guardian')], default='standard', max_length=50, verbose_name='Registration Form Type'),
        ),
    ]
