# Generated by Django 2.1.1 on 2018-09-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_legalsignature_agreed_by'),
        ('registration', '0005_auto_20180904_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationevent',
            name='legal_forms_guardian',
            field=models.ManyToManyField(help_text='The documents the parent/guardian of the event will need to agree to.', related_name='legal_forms_guardian', to='legal.LegalDocument'),
        ),
        migrations.AlterField(
            model_name='registrationevent',
            name='legal_forms',
            field=models.ManyToManyField(help_text='The documents the participant of the event will need to agree to.', to='legal.LegalDocument'),
        ),
        migrations.AlterField(
            model_name='registrationinvite',
            name='public_registration',
            field=models.BooleanField(blank=True, default=False, verbose_name='Public Registration'),
        ),
    ]
