# Generated by Django 2.1.1 on 2018-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180904_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='emergency_contact_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Second Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='emergency_phone_second',
            field=models.CharField(blank=True, max_length=25, verbose_name='Second Emergency Phone Contact'),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='emergency_relationship_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Second Emergency Contact Relationship'),
        ),
    ]
