# Generated by Django 2.1.5 on 2019-06-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180905_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='marketing_source',
            field=models.CharField(blank=True, help_text='Optional. Facebook? Friend? MRD event?', max_length=250, verbose_name='How did you find out about Wreckers?'),
        ),
    ]
